name: Marc Guyer
description: Ramblings - Mostly Code - Occasionally Useful
meta_description: "Marc Guyer | Ramblings - Mostly Code - Occasionally Useful"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://marc.guyer.me'
google_analytics: 'UA-69610431-1'
disqus: true
disqus_shortname: 'marcguyer'

gems:
  - jekyll-mentions

# Details for the RSS feed generator
url:            'http://marc.guyer.me'
author:         'Marc Guyer'
authorTitle:    'Software Architect'
authorTwitter:  'marcguyer'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
